// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr8oLZsIqsfsqiUCO9SjJfe1NX-34mNwo',
    appId: '1:645780450987:web:e4ae2905f23175006c51ee',
    messagingSenderId: '645780450987',
    projectId: 'dixonproject-eb289',
    authDomain: 'dixonproject-eb289.firebaseapp.com',
    storageBucket: 'dixonproject-eb289.firebasestorage.app',
    measurementId: 'G-22NXGYRZ8D',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvYhEU6tYbGZq74sG02q21irubCg_MorE',
    appId: '1:645780450987:ios:c02430165a8440506c51ee',
    messagingSenderId: '645780450987',
    projectId: 'dixonproject-eb289',
    storageBucket: 'dixonproject-eb289.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvYhEU6tYbGZq74sG02q21irubCg_MorE',
    appId: '1:645780450987:ios:c02430165a8440506c51ee',
    messagingSenderId: '645780450987',
    projectId: 'dixonproject-eb289',
    storageBucket: 'dixonproject-eb289.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr8oLZsIqsfsqiUCO9SjJfe1NX-34mNwo',
    appId: '1:645780450987:web:04009e420637d2af6c51ee',
    messagingSenderId: '645780450987',
    projectId: 'dixonproject-eb289',
    authDomain: 'dixonproject-eb289.firebaseapp.com',
    storageBucket: 'dixonproject-eb289.firebasestorage.app',
    measurementId: 'G-T5ZHHL1JL0',
  );
}
